namespace: blumleon
name: vrp
version: 1.1.6
readme: README.md
authors:
  - Leon Blum <blumleon@users.noreply.github.com>
description: Ansible Collection for CLI-based automation of Huawei VRP network devices.
license:
  - GPL-3.0-or-later
build_ignore:
  - tests
  - dist
  - '*.tar.gz'
  - .ruff_cache
  - .pytest_cache
  - pyproject.toml
  - .gitignore
tags:
  - network
  - huawei
  - vrp
  - cli
  - automation
dependencies:
  ansible.netcommon: ">=2.5.0"
repository: https://github.com/blumleon/ansible-vrp
documentation: https://github.com/blumleon/ansible-vrp#readme
homepage: https://github.com/blumleon/ansible-vrp
issues: https://github.com/blumleon/ansible-vrp/issues
